qlds:
  databases:
    - db_nghe_an1
  from:
    - qlds_nghean



#spring:
#  datasource:
#    url: jdbc:mysql://171.244.9.248:3306/
#    username: ghdc
#    password: ghdc@123
#    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9000
  application:
    name: transfer
