spring:
  jersey:
    application-path: /api
  application:
    name: ministry
  rabbitmq:
    host: 171.244.9.248
    port: 5672
    username: qlds
    password: ghdc@123
urlES: http://172.16.9.4:9200/
server:
  port: 9005
#logging:
#  file: log.log
#    servlet:
#        context-path: /